/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class it_paperdragon_sbt_LibNotify__ */

#ifndef _Included_it_paperdragon_sbt_LibNotify__
#define _Included_it_paperdragon_sbt_LibNotify__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     it_paperdragon_sbt_LibNotify__
 * Method:    notifyInitializeInternal
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_it_paperdragon_sbt_LibNotify_00024_notifyInitializeInternal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     it_paperdragon_sbt_LibNotify__
 * Method:    showNotificationInternal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_it_paperdragon_sbt_LibNotify_00024_showNotificationInternal
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     it_paperdragon_sbt_LibNotify__
 * Method:    notifyDestroyInternal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_it_paperdragon_sbt_LibNotify_00024_notifyDestroyInternal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
